name: Keep n8n Alive

on:
  schedule:
    - cron: "*/1 * * * *"
  workflow_dispatch:

jobs:
  curl:
    runs-on: ubuntu-latest
    steps:
      - name: Ping n8n Render
        run: |
          echo "⏰ $(date) - Pinging n8n..."
          curl -I https://n8n-kenji.onrender.com
